# Generated by Django 4.1 on 2022-08-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('timestamp_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('country', models.CharField(blank=True, max_length=40, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='Город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название клуба')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('timestamp_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('timestamp_start', models.DateTimeField(blank=True, verbose_name='Игра началась в ')),
                ('timestamp_end', models.DateTimeField(blank=True, verbose_name='Игра закончилась в ')),
                ('days_description', models.JSONField(verbose_name='Описание дней')),
                ('best_move', models.JSONField(verbose_name='Лучший ход')),
                ('result', models.CharField(choices=[('Mafia', 'Mafia'), ('City', 'City'), ('Draw', 'Draw')], max_length=5, verbose_name='Результат игры')),
                ('judge_comments', models.TextField(verbose_name='Комментарии судьи')),
                ('checksum', models.TextField(verbose_name='Контрольная сумма')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_game', to='projectmAPI.club', verbose_name='Принадлежность игры клубу')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Civilian', 'Civilian'), ('Сommissioner', 'Сommissioner'), ('Mafia', 'Mafia'), ('Don', 'Don'), ('Judge', 'Judge')], max_length=12, verbose_name='Роль в игре')),
                ('fouls', models.IntegerField(verbose_name='Количество фолов')),
                ('is_delete_from_game', models.BooleanField(verbose_name='Удален ли игрок из игры')),
                ('delete_reason', models.TextField(blank=True, verbose_name='Причина удаления')),
                ('points', models.FloatField(verbose_name='Итоговые очки за игру')),
                ('points_description', models.TextField(verbose_name='За что даны очки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_userm_mtm', to='projectmAPI.game', verbose_name='Игра')),
                ('userm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userm_game_mtm', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь игры и пользователя',
                'verbose_name_plural': 'Свяхи игр и пользователей',
            },
        ),
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_club', models.CharField(choices=[('Member', 'Member'), ('Judge', 'Judge'), ('President', 'President'), ('Vice-President', 'Vice-President')], max_length=14, verbose_name='Роль в клубе')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_userm_mtm', to='projectmAPI.club', verbose_name='Клуб')),
                ('userm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userm_club_mtm', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь клуба и пользователя',
                'verbose_name_plural': 'Связь клубов и пользователей',
            },
        ),
    ]
